### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by geyerbri** [pseudocereal/paisajes#7]
Hi Maria!

So, while you can decide what to name your repo, I would point out that this name is following the requirements of the old way of making a published website, which aren't required anymore.

I would suggest you rename this repo simply "paisajes" to make it shorter.

**Comment by geyerbri** [comment]
Maria,

It looks like you saw this message and took its advice. Once you've completed an issue, you should feel free to click the "Close issue" button below, or create a short comment acknowledging that you've considered the issue and then click "Close and comment" (the button changes if you type a comment).

**Comment by pseudocereal** [comment]
thank you!!
